/*
 *  Copyright 2012 by Texas Instruments Incorporated.
 *
 */

/*!
 * File generated by platform wizard. DO NOT MODIFY. 
 *
 */

package ti.sdo.ipc.examples.platforms.evmC6A8149.eve {
    module Platform;
}

/*
 *  @(#) ti.sdo.ipc.examples.platforms.evmC6A8149.eve; 1,0,0,; 11-7-2012 13:11:45; /db/vtree/library/trees/ipc/ipc-i09/src/ xlibrary

 */

