/*
 *  Copyright 2012 by Texas Instruments Incorporated.
 *
 */

/*!
 * File generated by platform wizard. DO NOT MODIFY. 
 *
 */

package ti.sdo.ipc.examples.platforms.evmTI813X.host {
    module Platform;
}

/*
 *  @(#) ti.sdo.ipc.examples.platforms.evmTI813X.host; 1,0,0,; 11-7-2012 13:12:24; /db/vtree/library/trees/ipc/ipc-i09/src/ xlibrary

 */

