/*
 *  Copyright 2012 by Texas Instruments Incorporated.
 *
 */

/*!
 * File generated by platform wizard. DO NOT MODIFY. 
 *
 */

package ti.sdo.ipc.examples.platforms.simVayu.eve2 {
    module Platform;
}

/*
 *  @(#) ti.sdo.ipc.examples.platforms.simVayu.eve2; 1,0,0,; 11-7-2012 13:13:11; /db/vtree/library/trees/ipc/ipc-i09/src/ xlibrary

 */

